local Config = require('config')

return Config:init()
  :event(require('events.gui_startup'))
  :event(require('events.open_uri'))
  :load(require('config.general'))
  :load(require('config.appearance'))
  :load(require('config.fonts'))
  :load(require('config.keys'))
  :load(require('config.domains'))
  :load(require('config.launch'))
  :load(require('config.wallpaper'))
  :load(require('plugins.tabline_wez'))
  :build()
