local Config = require('config')

return Config:init()
  :event(require('events.open_uri'))
  :append(require('config.performance'))
  :append(require('config.env'))
  :append(require('config.fonts'))
  :append(require('config.window'))
  :append(require('config.domains'))
  :append(require('config.launch'))
  :append(require('config.keys'))
  :build()
