local o = vim.o       -- global options
local w = vim.wo      -- window-local options
local b = vim.bo      -- buffer-local options

o.hidden = true
o.encoding = 'utf-8'
o.pumheight = 10
o.showmode = false
o.backup = false
o.ruler = true
o.mouse = 'a'
o.writebackup = false
o.splitbelow = true
o.splitright = true
o.smarttab = true
o.showtabline = 1
o.timeoutlen = 300
o.termguicolors = true
o.scrolloff = 8
-- o.clipboard = 'unnamedplus'
o.hlsearch = false
o.errorbells = false
o.ignorecase = true

w.wrap = false
w.cursorline = true
w.number = true
w.relativenumber = true
w.signcolumn = 'yes'
w.colorcolumn = '80'

b.tabstop = 4
b.shiftwidth = 4
b.softtabstop = 4
b.expandtab = true
b.smartindent = true
b.autoindent = true
b.swapfile = false
--b.undodir = '~/.config/nvim/undo'
b.undofile = true
