.PHONY: test

test:
	nvim --headless --noplugin -u tests/plenary/minimal_init.lua -c "PlenaryBustedDirectory tests/plenary/spec/ { minimal_init = 'tests/plenary/minimal_init.lua', sequential = true }"
