[hooks.apply.pre]
{{ if eq .chezmoi.os "windows" }}
command = "./$env:USERPROFILE/.local/share/chezmoi/home/.chezmoitemplates/scripts/windows/update-nvim-config-from-template.ps1"
{{ else }}
command = "./$HOME/.local/share/chezmoi/home/.chezmoitemplates/scripts/unix/update-nvim-config-from-template.sh"
{{ end }}
