#!/bin/bash

if type nvim &>/dev/null; then
	alias v='nvim'
fi

# Use eza to list files
if type eza &>/dev/null; then
	alias ls='eza --icons'
	alias ll='eza -alF --icons'
	alias la='eza -aF --icons'
	alias l='eza -F --icons'
	alias lt='eza -alF --tree --level=2 --git --icons'
fi

if type bat &>/dev/null; then
	alias cat='bat'
fi
