# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json
# Ref: https://github.com/jesseduffield/lazydocker/blob/master/docs/Config.md
# TODO: Learn Go template and config lazydocker
