---@class dotfiles.lsp.Language
---@field parsers? string[] Tree-sitter parser names, not buffer filetypes.
---@field tools? string[] Mason packages; installing a tool does not enable a server.
---@field servers? table<string, vim.lsp.Config>
---@field formatters? table<string, conform.FiletypeFormatter>
---@field linters? table<string, string[]>
---@field lint_on_save? boolean Defaults to true for this module's linters; false wins when merged.
---@field dap? string[] Adapters managed by mason-nvim-dap; omit plugin-owned adapters.
---@field neotest? fun(): neotest.Adapter

---@class dotfiles.lsp.Registry
---@field parsers string[]
---@field tools string[]
---@field servers table<string, vim.lsp.Config>
---@field formatters table<string, conform.FiletypeFormatter>
---@field linters table<string, string[]>
---@field lint_on_save table<string, boolean>
---@field dap string[]
---@field get_neotest_adapters fun(): neotest.Adapter[]
